#================= archiverr/core/identity.py =================#
# This module contains functions for generating canonical identifiers for tracks based on their metadata.
# The canonical ID is a unique identifier that can be used to track the same track across different library imports, even if the track ID or persistent ID changes. The canonical ID is generated by hashing a combination of normalized metadata fields such as artist, album, title, and duration. This allows us to identify the same track even if the track ID or persistent ID changes due to library updates or changes in the source data.
#
################################################################


from archiverr.core.normalization import normalize_text as normalize

import hashlib


def build_canonical_id(track) -> str:
    """
    Generates a stable ID for deduplication across all sources.
    """

    # --------------------------
    # 1. STRONGEST CASE: ISRC
    # --------------------------
    if getattr(track, "isrc", None):
        return f"isrc:{track.isrc}"

    # --------------------------
    # 2. STRUCTURAL MATCH
    # --------------------------
    artist = normalize(track.artist)
    title = normalize(track.title)
    album = normalize(getattr(track, "album", ""))

    duration = getattr(track, "duration_ms", None)
    duration_bucket = int(duration / 1000) if duration else 0

    base = f"{artist}|{title}|{album}|{duration_bucket}"

    return "hash:" + hashlib.sha1(base.encode("utf-8")).hexdigest()